### ISSUE TITLE
Postman is failing on Step 5 in the Base config using runner

### ISSUE THREAD

**Issue by gahlberg** [fortinet-solutions-cse/postman_collections#8]
Postman is failing on Step 5 Add Devices in the Base Config when using Runner, getting the following error:
Task completed | AssertionError: Failed to add some devices: expected 4 to equal 0

**Comment by dmitryperets** [comment]
HI @gahlberg, 

Is it reproducible consistently? 
Can you check in your FortiManager's Task Monitor (System Settings -> Task Monitor)? You should see the task adding the devices, and I suspect that it really failed. Wondering with what exact error. 

Because the test in our Postman call is checking the value of `num_err` in the response, which is the number of failed devices. We expect this number to be 0, and the above message says that it got 4 (so 4 failed out of 4). 

We've seen it for a few people during a workshop, and if they would simply repeat the attempt, it would just work fine. Hence, we suspect that it might be related to a timeout, e.g. caused by high load on the virtual lab instances. If that's the case, then I don't think it can be solved in the Postman call...

**Comment by gahlberg** [comment]
I think it may have been an anomaly and an issue with the lab I spun up, I started another lab environment and pulled in a fresh copy of the postman_collection for this and it worked.  Thanks for the quick followup.
